window.HP_CLEARANCE_DATA = [
  {
    id: "CLEARANCE-YA292",
    brand: "CLEARANCE",
    series: "YA292",
    model: "YA292",
    name: "YA292 休闲椅",
    configuration: "休闲椅",
    color: "千鸟格, 后背棕色",
    dimensions: "常规",
    price: 1848,
    photo: "assets/clearance/YA292.jpg"
  },
  {
    id: "CLEARANCE-YA243",
    brand: "CLEARANCE",
    series: "YA243",
    model: "YA243",
    name: "YA243 休闲椅",
    configuration: "休闲椅",
    color: "橙色",
    dimensions: "",
    price: 2156,
    photo: "assets/clearance/YA243.jpg"
  },
  {
    id: "CLEARANCE-A2530",
    brand: "CLEARANCE",
    series: "A2530",
    model: "A2530",
    name: "A2530 餐椅",
    configuration: "餐椅",
    color: "浅灰",
    dimensions: "",
    price: 350,
    photo: "assets/clearance/A2530.jpg"
  },
  {
    id: "CLEARANCE-A01-GRAY",
    brand: "CLEARANCE",
    series: "A01厚",
    model: "A01厚",
    name: "A01厚 马鞍椅",
    configuration: "马鞍椅",
    color: "灰色",
    dimensions: "49 x 55 x 81",
    price: 380,
    photo: "assets/clearance/A01.jpg"
  },
  {
    id: "CLEARANCE-A01-ORANGE",
    brand: "CLEARANCE",
    series: "A01厚",
    model: "A01厚",
    name: "A01厚 马鞍椅",
    configuration: "马鞍椅",
    color: "橙色",
    dimensions: "49 x 55 x 81",
    price: 380,
    photo: "assets/clearance/A01.jpg"
  },
  {
    id: "CLEARANCE-YA193",
    brand: "CLEARANCE",
    series: "YA193升降",
    model: "YA193升降",
    name: "YA193升降 吧椅",
    configuration: "吧椅",
    color: "不锈钢拉丝本色架子 / 红色",
    dimensions: "",
    price: 1518,
    photo: "assets/clearance/YA193.jpg"
  },
  {
    id: "CLEARANCE-YA144",
    brand: "CLEARANCE",
    series: "YA144",
    model: "YA144",
    name: "YA144 吧椅",
    configuration: "吧椅",
    color: "橙色黑钛架子",
    dimensions: "",
    price: 1430,
    photo: "assets/clearance/YA144.jpg"
  },
  {
    id: "CLEARANCE-A2515B-DARK",
    brand: "CLEARANCE",
    series: "A2515B",
    model: "A2515B",
    name: "A2515B 餐椅",
    configuration: "餐椅",
    color: "深灰",
    dimensions: "常规",
    price: 380,
    photo: "assets/clearance/A2515B.jpg"
  },
  {
    id: "CLEARANCE-A2515B-LIGHT",
    brand: "CLEARANCE",
    series: "A2515B",
    model: "A2515B",
    name: "A2515B 餐椅",
    configuration: "餐椅",
    color: "浅灰",
    dimensions: "",
    price: 380,
    photo: "assets/clearance/A2515B.jpg"
  },
  {
    id: "CLEARANCE-A2433",
    brand: "CLEARANCE",
    series: "A2433",
    model: "A2433",
    name: "A2433 餐椅",
    configuration: "餐椅",
    color: "棕色",
    dimensions: "常规",
    price: 450,
    photo: "assets/clearance/A2433.jpg"
  },
  {
    id: "CLEARANCE-A2437-LIGHT",
    brand: "CLEARANCE",
    series: "A2437",
    model: "A2437",
    name: "A2437 餐椅",
    configuration: "餐椅",
    color: "浅灰",
    dimensions: "",
    price: 450,
    photo: "assets/clearance/A2437.jpg"
  },
  {
    id: "CLEARANCE-A2437-ORANGE",
    brand: "CLEARANCE",
    series: "A2437",
    model: "A2437",
    name: "A2437 餐椅",
    configuration: "餐椅",
    color: "橙色",
    dimensions: "",
    price: 450,
    photo: "assets/clearance/A2437.jpg"
  },
  {
    id: "CLEARANCE-YA140",
    brand: "CLEARANCE",
    series: "YA140",
    model: "YA140",
    name: "YA140 吧椅",
    configuration: "吧椅",
    color: "棕色",
    dimensions: "",
    price: 1496,
    photo: "assets/clearance/YA140.jpg"
  },
  {
    id: "CLEARANCE-T001-BLACK",
    brand: "CLEARANCE",
    series: "T-001",
    model: "T-001",
    name: "T-001 休闲椅",
    configuration: "休闲椅",
    color: "黑色",
    dimensions: "82 x 83 x 80",
    price: 1078,
    photo: "assets/clearance/T001-BLACK.jpg"
  },
  {
    id: "CLEARANCE-T001-REDBROWN",
    brand: "CLEARANCE",
    series: "T-001",
    model: "T-001",
    name: "T-001 休闲椅",
    configuration: "休闲椅",
    color: "红棕色",
    dimensions: "82 x 83 x 80",
    price: 1078,
    photo: "assets/clearance/T001-REDBROWN.jpg"
  }
].map((item) => ({
  ...item,
  materials: ["清货价"],
  priceOptions: [item.price],
  priceIsFinal: true,
  source: "清库存订货单 2026-01-06",
  description: `${item.configuration} / ${item.color}${item.dimensions ? ` / ${item.dimensions}` : ""}`,
  details: `${item.configuration} / ${item.color}`
}));
