window.HP_CLEARANCE_DATA = [
  {
    id: "CLEARANCE-YA292",
    brand: "CLEARANCE",
    series: "YA292",
    model: "YA292",
    name: "YA292 ä¼‘é—²æ¤…",
    configuration: "ä¼‘é—²æ¤…",
    color: "åƒé¸Ÿæ ¼, åŽèƒŒæ£•è‰²",
    dimensions: "å¸¸è§„",
    price: 1848,
    photo: "assets/clearance/YA292-recrop.jpg"
  },
  {
    id: "CLEARANCE-YA243",
    brand: "CLEARANCE",
    series: "YA243",
    model: "YA243",
    name: "YA243 ä¼‘é—²æ¤…",
    configuration: "ä¼‘é—²æ¤…",
    color: "æ©™è‰²",
    dimensions: "",
    price: 2156,
    photo: "assets/clearance/YA243-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2530",
    brand: "CLEARANCE",
    series: "A2530",
    model: "A2530",
    name: "A2530 é¤æ¤…",
    configuration: "é¤æ¤…",
    color: "æµ…ç°",
    dimensions: "",
    price: 350,
    photo: "assets/clearance/A2530-recrop.jpg"
  },
  {
    id: "CLEARANCE-A01-GRAY",
    brand: "CLEARANCE",
    series: "A01åŽš",
    model: "A01åŽš",
    name: "A01åŽš é©¬éžæ¤…",
    configuration: "é©¬éžæ¤…",
    color: "ç°è‰²",
    dimensions: "49 x 55 x 81",
    price: 380,
    photo: "assets/clearance/A01-recrop.jpg"
  },
  {
    id: "CLEARANCE-A01-ORANGE",
    brand: "CLEARANCE",
    series: "A01åŽš",
    model: "A01åŽš",
    name: "A01åŽš é©¬éžæ¤…",
    configuration: "é©¬éžæ¤…",
    color: "æ©™è‰²",
    dimensions: "49 x 55 x 81",
    price: 380,
    photo: "assets/clearance/A01-recrop.jpg"
  },
  {
    id: "CLEARANCE-YA193",
    brand: "CLEARANCE",
    series: "YA193å‡é™",
    model: "YA193å‡é™",
    name: "YA193å‡é™ å§æ¤…",
    configuration: "å§æ¤…",
    color: "ä¸é”ˆé’¢æ‹‰ä¸æœ¬è‰²æž¶å­ / çº¢è‰²",
    dimensions: "",
    price: 1518,
    photo: "assets/clearance/YA193-recrop.jpg"
  },
  {
    id: "CLEARANCE-YA144",
    brand: "CLEARANCE",
    series: "YA144",
    model: "YA144",
    name: "YA144 å§æ¤…",
    configuration: "å§æ¤…",
    color: "æ©™è‰²é»‘é’›æž¶å­",
    dimensions: "",
    price: 1430,
    photo: "assets/clearance/YA144-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2515B-DARK",
    brand: "CLEARANCE",
    series: "A2515B",
    model: "A2515B",
    name: "A2515B é¤æ¤…",
    configuration: "é¤æ¤…",
    color: "æ·±ç°",
    dimensions: "å¸¸è§„",
    price: 380,
    photo: "assets/clearance/A2515B-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2515B-LIGHT",
    brand: "CLEARANCE",
    series: "A2515B",
    model: "A2515B",
    name: "A2515B é¤æ¤…",
    configuration: "é¤æ¤…",
    color: "æµ…ç°",
    dimensions: "",
    price: 380,
    photo: "assets/clearance/A2515B-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2433",
    brand: "CLEARANCE",
    series: "A2433",
    model: "A2433",
    name: "A2433 é¤æ¤…",
    configuration: "é¤æ¤…",
    color: "æ£•è‰²",
    dimensions: "å¸¸è§„",
    price: 450,
    photo: "assets/clearance/A2433-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2437-LIGHT",
    brand: "CLEARANCE",
    series: "A2437",
    model: "A2437",
    name: "A2437 é¤æ¤…",
    configuration: "é¤æ¤…",
    color: "æµ…ç°",
    dimensions: "",
    price: 450,
    photo: "assets/clearance/A2437-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2437-ORANGE",
    brand: "CLEARANCE",
    series: "A2437",
    model: "A2437",
    name: "A2437 é¤æ¤…",
    configuration: "é¤æ¤…",
    color: "æ©™è‰²",
    dimensions: "",
    price: 450,
    photo: "assets/clearance/A2437-recrop.jpg"
  },
  {
    id: "CLEARANCE-YA140",
    brand: "CLEARANCE",
    series: "YA140",
    model: "YA140",
    name: "YA140 å§æ¤…",
    configuration: "å§æ¤…",
    color: "æ£•è‰²",
    dimensions: "",
    price: 1496,
    photo: "assets/clearance/YA140-recrop.jpg"
  },
  {
    id: "CLEARANCE-T001-BLACK",
    brand: "CLEARANCE",
    series: "T-001",
    model: "T-001",
    name: "T-001 ä¼‘é—²æ¤…",
    configuration: "ä¼‘é—²æ¤…",
    color: "é»‘è‰²",
    dimensions: "82 x 83 x 80",
    price: 1078,
    photo: "assets/clearance/T001-BLACK-recrop.jpg"
  },
  {
    id: "CLEARANCE-T001-REDBROWN",
    brand: "CLEARANCE",
    series: "T-001",
    model: "T-001",
    name: "T-001 ä¼‘é—²æ¤…",
    configuration: "ä¼‘é—²æ¤…",
    color: "çº¢æ£•è‰²",
    dimensions: "82 x 83 x 80",
    price: 1078,
    photo: "assets/clearance/T001-REDBROWN-recrop.jpg"
  }
].map((item) => ({
  ...item,
  materials: ["æ¸…è´§ä»·"],
  priceOptions: [item.price],
  priceIsFinal: true,
  source: "æ¸…åº“å­˜è®¢è´§å• 2026-01-06",
  description: `${item.configuration} / ${item.color}${item.dimensions ? ` / ${item.dimensions}` : ""}`,
  details: `${item.configuration} / ${item.color}`
}));

