window.HP_CLEARANCE_DATA = [
  {
    id: "CLEARANCE-YA292",
    brand: "CLEARANCE",
    series: "YA292",
    model: "YA292",
    name: "YA292 休闲椅",
    configuration: "休闲椅",
    color: "千鸟格,后背棕色",
    dimensions: "常规",
    supplierCost: 840,
    price: 1848,
    photo: "assets/clearance/YA292-recrop.jpg"
  },
  {
    id: "CLEARANCE-YA243",
    brand: "CLEARANCE",
    series: "YA243",
    model: "YA243",
    name: "YA243 休闲椅",
    configuration: "休闲椅",
    color: "橙色",
    dimensions: "",
    supplierCost: 980,
    price: 2156,
    photo: "assets/clearance/YA243-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2530",
    brand: "CLEARANCE",
    series: "A2530",
    model: "A2530",
    name: "A2530 餐椅",
    configuration: "餐椅",
    color: "浅灰",
    dimensions: "",
    supplierCost: 155,
    price: 350,
    photo: "assets/clearance/A2530-recrop.jpg"
  },
  {
    id: "CLEARANCE-A01-GRAY",
    brand: "CLEARANCE",
    series: "A01厚",
    model: "A01厚",
    name: "A01厚 马鞍椅",
    configuration: "马鞍椅",
    color: "灰色",
    dimensions: "49 x 55 x 81",
    supplierCost: 165,
    price: 380,
    photo: "assets/clearance/A01-GRAY.jpg"
  },
  {
    id: "CLEARANCE-A01-ORANGE",
    brand: "CLEARANCE",
    series: "A01厚",
    model: "A01厚",
    name: "A01厚 马鞍椅",
    configuration: "马鞍椅",
    color: "橙色",
    dimensions: "49 x 55 x 81",
    supplierCost: 165,
    price: 380,
    photo: "assets/clearance/A01-ORANGE.jpg"
  },
  {
    id: "CLEARANCE-YA193",
    brand: "CLEARANCE",
    series: "YA193升降",
    model: "YA193升降",
    name: "YA193升降 吧椅",
    configuration: "吧椅",
    color: "不锈钢拉丝本色架子/红色",
    dimensions: "",
    supplierCost: 690,
    price: 1518,
    photo: "assets/clearance/YA193-recrop.jpg"
  },
  {
    id: "CLEARANCE-YA144",
    brand: "CLEARANCE",
    series: "YA144",
    model: "YA144",
    name: "YA144 吧椅",
    configuration: "吧椅",
    color: "橙色黑钛架子",
    dimensions: "",
    supplierCost: 650,
    price: 1430,
    photo: "assets/clearance/YA144-orange-20260706.jpg"
  },
  {
    id: "CLEARANCE-A2515B-DARK",
    brand: "CLEARANCE",
    series: "A2515B",
    model: "A2515B",
    name: "A2515B 餐椅",
    configuration: "餐椅",
    color: "深灰",
    dimensions: "常规",
    supplierCost: 170,
    price: 380,
    photo: "assets/clearance/A2515B-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2515B-LIGHT",
    brand: "CLEARANCE",
    series: "A2515B",
    model: "A2515B",
    name: "A2515B 餐椅",
    configuration: "餐椅",
    color: "浅灰",
    dimensions: "",
    supplierCost: 170,
    price: 380,
    photo: "assets/clearance/A2515B-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2433",
    brand: "CLEARANCE",
    series: "A2433",
    model: "A2433",
    name: "A2433 餐椅",
    configuration: "餐椅",
    color: "棕色",
    dimensions: "常规",
    supplierCost: 195,
    price: 450,
    photo: "assets/clearance/A2433-recrop.jpg"
  },
  {
    id: "CLEARANCE-A2437-LIGHT",
    brand: "CLEARANCE",
    series: "A2437",
    model: "A2437",
    name: "A2437 餐椅",
    configuration: "餐椅",
    color: "浅灰",
    dimensions: "",
    supplierCost: 185,
    price: 450,
    photo: "assets/clearance/A2437-LIGHT.jpg"
  },
  {
    id: "CLEARANCE-A2437-ORANGE",
    brand: "CLEARANCE",
    series: "A2437",
    model: "A2437",
    name: "A2437 餐椅",
    configuration: "餐椅",
    color: "橙色",
    dimensions: "",
    supplierCost: 185,
    price: 450,
    photo: "assets/clearance/A2437-ORANGE.jpg"
  },
  {
    id: "CLEARANCE-YA140",
    brand: "CLEARANCE",
    series: "YA140",
    model: "YA140",
    name: "YA140 吧椅",
    configuration: "吧椅",
    color: "棕色",
    dimensions: "",
    supplierCost: 680,
    price: 1496,
    photo: "assets/clearance/YA140-correct-20260706.jpg"
  },
  {
    id: "CLEARANCE-T001-BLACK",
    brand: "CLEARANCE",
    series: "T-001",
    model: "T-001",
    name: "T-001 休闲椅",
    configuration: "休闲椅",
    color: "黑色",
    dimensions: "82 x 83 x 80",
    supplierCost: 490,
    price: 1078,
    photo: "assets/clearance/T001-BLACK-recrop.jpg"
  },
  {
    id: "CLEARANCE-T001-REDBROWN",
    brand: "CLEARANCE",
    series: "T-001",
    model: "T-001",
    name: "T-001 休闲椅",
    configuration: "休闲椅",
    color: "红棕色",
    dimensions: "82 x 83 x 80",
    supplierCost: 490,
    price: 1078,
    photo: "assets/clearance/T001-REDBROWN-recrop.jpg"
  },
  {
    id: "CLEARANCE-A5401-RICE",
    brand: "CLEARANCE",
    series: "A5401",
    model: "A5401",
    name: "A5401 餐椅",
    configuration: "餐椅",
    color: "米色",
    dimensions: "",
    supplierCost: 245,
    price: 550,
    photo: "assets/clearance/A5401-RICE.jpg"
  },
  {
    id: "CLEARANCE-A5401-BLACK",
    brand: "CLEARANCE",
    series: "A5401",
    model: "A5401",
    name: "A5401 餐椅",
    configuration: "餐椅",
    color: "黑色",
    dimensions: "",
    supplierCost: 245,
    price: 550,
    photo: "assets/clearance/A5401-BLACK.jpg"
  },
  {
    id: "CLEARANCE-A3412C-BLACK",
    brand: "CLEARANCE",
    series: "A3412C款",
    model: "A3412C款",
    name: "A3412C款 餐椅",
    configuration: "餐椅",
    color: "黑色",
    dimensions: "",
    supplierCost: 160,
    price: 360,
    photo: "assets/clearance/A3412C-BLACK.jpg"
  },
  {
    id: "CLEARANCE-A3412C-WINERED",
    brand: "CLEARANCE",
    series: "A3412C款",
    model: "A3412C款",
    name: "A3412C款 餐椅",
    configuration: "餐椅",
    color: "酒红",
    dimensions: "",
    supplierCost: 160,
    price: 360,
    photo: "assets/clearance/A3412C-WINERED.jpg"
  },
  {
    id: "CLEARANCE-A5253-GREEN",
    brand: "CLEARANCE",
    series: "A5253带转",
    model: "A5253带转",
    name: "A5253带转 餐椅",
    configuration: "餐椅",
    color: "绿色麻布",
    dimensions: "",
    supplierCost: 195,
    price: 450,
    photo: "assets/clearance/A5253-GREEN.jpg"
  },
  {
    id: "CLEARANCE-YA157",
    brand: "CLEARANCE",
    series: "YA157",
    model: "YA157",
    name: "YA157 餐椅",
    configuration: "餐椅",
    color: "米色麻布，黑色架子，坐高65",
    dimensions: "常规",
    supplierCost: 360,
    price: 800,
    photo: "assets/clearance/YA157.jpg"
  }
].map((item) => ({
  ...item,
  materials: ["清货价"],
  priceOptions: [item.price],
  priceIsFinal: true,
  source: "嗨一家清库存订货单 2026-01-06 / 张1月6日订货单(1).et",
  description: `${item.configuration} / ${item.color}${item.dimensions ? ` / ${item.dimensions}` : ""}`,
  details: `${item.configuration} / ${item.color}`
}));
